/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_RTCLIENT_H_
#define JSONRPC_CPP_STUB_RTCLIENT_H_

#include <jsonrpccpp/client.h>

class rtClient : public jsonrpc::Client
{
    public:
        rtClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value register_team(const std::string& action, const Json::Value& your_json) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["action"] = action;
            p["your_json"] = your_json;
            Json::Value result = this->CallMethod("register team",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_RTCLIENT_H_
